### Bootstrap Sampling

Below is an array of the possible values you can obtain from a die.  Let's consider different methods of sampling from these values.

In [1]:
import numpy as np
np.random.seed(42)

die_vals = np.array([1,2,3,4,5,6])

1. Take a random sample of 20 values from **die_vals** using the code below, then answer the question in the first quiz below.

In [2]:
np.random.choice(die_vals, size=20)

array([4, 5, 3, 5, 5, 2, 3, 3, 3, 5, 4, 3, 6, 5, 2, 4, 6, 6, 2, 4])

`2.` Use the code below to choose another sample from **die_vals**, then answer the question in the first quiz below.

In [3]:
np.random.choice(die_vals, replace=False, size=20)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [7]:
proportions = [np.random.choice(die_vals,21) for _ in range(10000)]

In [8]:
proportions

[array([1, 2, 6, 3, 5, 3, 3, 1, 3, 4, 4, 1, 3, 4, 3, 4, 4, 1, 3, 2, 1]),
 array([2, 6, 5, 6, 5, 2, 5, 6, 2, 4, 1, 6, 2, 6, 4, 4, 4, 1, 6, 5, 4]),
 array([5, 6, 1, 3, 4, 3, 6, 5, 3, 2, 1, 4, 5, 3, 6, 6, 6, 4, 6, 6, 4]),
 array([5, 4, 1, 4, 1, 4, 1, 6, 3, 1, 6, 1, 6, 5, 5, 2, 5, 6, 5, 4, 2]),
 array([1, 5, 6, 3, 4, 4, 4, 6, 3, 2, 5, 5, 1, 5, 1, 4, 4, 4, 4, 1, 3]),
 array([4, 3, 1, 4, 4, 3, 5, 4, 5, 4, 2, 6, 3, 6, 5, 2, 6, 2, 6, 3, 4]),
 array([4, 4, 4, 4, 3, 5, 3, 4, 3, 4, 3, 4, 6, 4, 2, 2, 6, 1, 6, 3, 2]),
 array([6, 1, 4, 1, 4, 6, 2, 1, 1, 4, 6, 3, 2, 5, 4, 6, 2, 2, 3, 1, 4]),
 array([2, 2, 4, 3, 6, 1, 1, 5, 1, 1, 4, 5, 5, 3, 1, 2, 4, 6, 6, 2, 5]),
 array([5, 1, 4, 4, 1, 1, 4, 5, 2, 6, 2, 5, 3, 4, 1, 3, 6, 5, 4, 3, 3]),
 array([5, 1, 2, 4, 2, 5, 3, 2, 6, 2, 5, 2, 1, 5, 3, 2, 1, 5, 5, 2, 4]),
 array([5, 5, 5, 2, 3, 3, 6, 3, 4, 1, 4, 6, 2, 2, 6, 5, 1, 6, 1, 3, 2]),
 array([6, 1, 5, 1, 2, 6, 5, 1, 5, 1, 5, 5, 4, 3, 4, 3, 4, 6, 2, 1, 1]),
 array([6, 4, 1, 2, 3, 6, 4, 5, 1, 4, 6, 1, 3, 2, 6